### ISSUE TITLE
Question: is it possible to post tweet with geolocation information?

### ISSUE THREAD

**Issue by hy9be** [lapastillaroja/twitter4j-android-sample#1]
There are methods for querying geolocation information. But I did not find any api to attached geolocation information to a tweet posted by the Twitter.updateStatus(...). Do you have any directions?

**Comment by lapastillaroja** [comment]
Sorry for the late reply.
Twitter published some months ago and [Android official SDK](https://github.com/twitter/twitter-kit-android).
I recommend you to use that instead twitter-4j.
About the geolocation question, I don't know if it possible but I think it should be.
